// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1O8VlrHmrNMd09dCS-f_7pV1ER_FYR-Q',
    appId: '1:155194106183:web:5e5be4212b61a603ae2c62',
    messagingSenderId: '155194106183',
    projectId: 'niajiri-206f4',
    authDomain: 'niajiri-206f4.firebaseapp.com',
    storageBucket: 'niajiri-206f4.appspot.com',
    measurementId: 'G-5JQPQJB9NF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGwb72pzAiu99DRi0lYYDapZZR95QDVZI',
    appId: '1:155194106183:android:2d5b91484208f0c3ae2c62',
    messagingSenderId: '155194106183',
    projectId: 'niajiri-206f4',
    storageBucket: 'niajiri-206f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpz8tAHNy5-gljqGRHGQu-_qXfL3J2bpM',
    appId: '1:155194106183:ios:5e09d8dae1973e22ae2c62',
    messagingSenderId: '155194106183',
    projectId: 'niajiri-206f4',
    storageBucket: 'niajiri-206f4.appspot.com',
    iosClientId: '155194106183-6j507tjr8ecbjvd0nka2nq7er38ebefh.apps.googleusercontent.com',
    iosBundleId: 'com.example.riziki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpz8tAHNy5-gljqGRHGQu-_qXfL3J2bpM',
    appId: '1:155194106183:ios:5e09d8dae1973e22ae2c62',
    messagingSenderId: '155194106183',
    projectId: 'niajiri-206f4',
    storageBucket: 'niajiri-206f4.appspot.com',
    iosClientId: '155194106183-6j507tjr8ecbjvd0nka2nq7er38ebefh.apps.googleusercontent.com',
    iosBundleId: 'com.example.riziki',
  );
}
